# Tensors in Pytorch

Tensors are data structures, `(arrays in higher dimensional array)`. It is specialized multi dimensional array designed for mathematical and computational efficiency. 
Dimension of tension refers to how many direction it is spanning. 

## Example of Tensors

1. Zero dimensional tensors : Scalars, which is not spanned in any direction.
    - Represents a single value and often used for simple metrics or constants. 
    - loss value : After a forward pass. the loss function computes a single scalar value indicatinf the difference between the predicted and actual outputs. 
    - Example : 5.0 or -3.14


2. 1- Dimensional tensors : Vectors (arrays)
    - Represents a sequence or collection of values.
    - Feature vector: In NLP, each word in a sentence maybe represented as a 1D vector using embeddings.
    - Example: [0.12,0.84,0.33] (a word embedding vector from a pre trained model like word2vec or Glove)

3. 2- Dimensional tensors (a 2D grid of numbers) : Matrices
    - Represents tabular or grid like data
    - Grayscale Image : A grayscale image can be represented as a 2d tensor, where each entry corresponds to the pixel intensity.
    - Example: [[0,255,129],[34,90,180]]

4.  Coloured Images : 3d tensors
    - Adds a third dimension, often used for stacking data.
    - RGB images : A single RGB image is represented as a 3D tensor (width * height * channels)
    - Examples RGB Image :  eg (256*256) : shape(256,256,3)


5. Batches of RGB Images : 4D Tensors
    - Batches of RGB images: A dataset of coloured images is represented as a 4D tensor (batch size * width * height*channels)
    - A batch of 32 images, each size of 128*126 with 3 color channels (RGB), would have shape [32,128,128,3]


6. Video data : 5d tensors
    - Adds a time dimension for data that changes over time . (eg video frame)
    - Video clips: Represented as a sequence of frames, where each frame is an RGB image.
    - A batch of 10 video clips, each with 16 frames of size 64*64 and 3 channels (RGB) would have shape [10,1664,64,3]

### Why tensors are useful ?

1. Mathematical Operations
    - Tensors enables efficient mathematical computations (addition, multiplication,dot product, etc) for neural network operations.

2. Representation of Real world data
    - Data like images, audio, video and text can be represented as tensors:
    - Images : Represented as 3D tensors (width * height *channels)
    - Text: Tokenized and represented as 2d or 3d tensors (sequence length * embedding size) 


3. Efficient computations
    - Tensors are optimized for hardware accelerations, allowing computations on GPUs or TPUs, which are crucial for training deep learning models.

#### Why Tensors are used in deep learning ?

1. Data storage : Training data (images,text etc) is stored in tensors.
2. Weight ans biases : The learnable parameters of nueral network (weight, biases) are stored as tensors. 
3. Matrix operations : Neural network involve operations like matrix multiplication, dor products and broadcasting - all performed using tensors.
4. Training process : During forward passes, tensors flow through the network. Gradients represented as tensors are calculated during the backward passf. 

In [2]:
import torch
print(torch.__version__)

d:\python_env\Intro_to_PyTorch\.venv\lib\site-packages\torch\_subclasses\functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.12.0+cpu


*Creating a tensor*

In [3]:
#empty
a=torch.empty(2,3)
type(a)

torch.Tensor

In [4]:
# using zeros
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# using rand
torch.rand(2,3)

tensor([[0.1890, 0.4447, 0.8062],
        [0.5751, 0.5676, 0.5766]])

In [7]:
# use of seed: defining seed to make value of rand same everytime
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# other ways

print("using arrays",torch.arange(0,10)) # range  can be provided step as well 

print("using linspace",torch.linspace(0,10,10))  # Linearly spaced, created 10 evenly spaced values from 0 to 10. 

print("using eye",torch.eye(5))  # identity matrix of 5 * 5 

print("using full", torch.full((3,3),5)) # tensor of 3 cross 3 and each item should be 5. 

using arrays tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor shapes**

In [10]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape 

torch.Size([2, 3])

In [11]:
torch.empty_like(x)  # similar tensor like x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [14]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

``` Text 
 Reason : Inside x tensor, all item is integer, where rand generates float from 0 t0 10. 

**Tensor Data Type**

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.1],dtype=torch.int32)   # dtype=torch.float64 as our need

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# using to()

x.to( torch.float32)

# the error above can be handled like this
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])



###  Data Type Reference Table

| TensorFlow API | Short Alias (`dtype`) | Description | Common Use Case |
| :--- | :--- | :--- | :--- |
| `tf.float32` | `tf.dtypes.float32` | 32-bit single-precision float | Default for weights & activations |
| `tf.float16` | `tf.dtypes.float16` | 16-bit half-precision float | Mixed-precision training (saves VRAM) |
| `tf.bfloat16` | `tf.dtypes.bfloat16` | 16-bit Brain float (Truncated `float32`) | TPU/GPU acceleration |
| `tf.float64` | `tf.dtypes.float64` | 64-bit double-precision float | High-precision scientific computing |
| `tf.int32` | `tf.dtypes.int32` | 32-bit signed integer | Indexing, loop counters, shapes |
| `tf.int64` | `tf.dtypes.int64` | 64-bit signed integer | Large dataset IDs, tokenizers |
| `tf.uint8` | `tf.dtypes.uint8` | 8-bit unsigned integer | Raw image pixels (0-255), Quantization |
| `tf.bool` | `tf.dtypes.bool` | Boolean (`True` / `False`) | Logical masking, boolean indexing |
| `tf.string` | `tf.dtypes.string` | Variable-length byte string | Text processing, file paths |


**Mathematical operations**

**1. Scalar Operations**

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

In [ ]:
# addition
x+2

# substraction
x-4

# Multiplication
x*3

# divison
x/2

# int divison
(x*100)//3

# mod
((x*100)//3)%2

# power
x**2

tensor([[0.0588, 0.4905],
        [0.2785, 0.0611]])

**2. Element wise Operation**

Every operations is performed element wise

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

# add
a+b

# multiply
a*b

# subs
a-b

# division
a/b

# power
a**b

#mod
a%b

tensor([[0.1156, 0.3687, 0.9053],
        [0.0765, 0.3039, 0.0547]])

In [ ]:
# absolute (abs)
c=torch.tensor([1,3,4,5])
torch.abs(c)

# negative
d=torch.tensor([1.9,2.4,3.7,4.4])
torch.neg(d)

# round
torch.round(d)

#ceil
torch.ceil(d)       # It rounds every number in tensor up to the nearest whole integer.

# floor does the exact opposite of ceil. It forcefully rounds every decimal number down to the nearest whole integer, dragging it down to the "floor."
torch.floor(d)

#clamp
torch.clamp(d,min=2.0,max=4.0) # setting physical boundaries (a floor and a ceiling) for values.

tensor([2.0000, 2.4000, 3.7000, 4.0000])

```Text
Exploding gradients can cause numbers to become violently large during training, breaking the neural network. We use `torch.clamp()` to put safety rails on the data, forcing wild values to stay within a stable, readable range like `(-1.0 or 1.0)`. 
```

**3. Reduction Operation**

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 6., 2.],
        [9., 5., 0.]])

In [ ]:
# sum
torch.sum(e)

# sum along cols
torch.sum(e,dim=0)

# sum along row
torch.sum(e,dim=1)

tensor([13., 14.])

In [ ]:
# mean
torch.mean(e)

#mean along vol
torch.mean(e,dim=0)

tensor([7.0000, 5.5000, 1.0000])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1464)

In [ ]:
# variance
torch.var(e)

tensor(9.9000)

In [ ]:
# argmax
torch.argmax(e) # position of bigger element

tensor(3)

In [ ]:
#argmin
torch.argmin(e)

tensor(5)

**Matrix Operation**

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

# matrix multiplication
torch.matmul(f,g)

tensor([[32, 46],
        [15, 25]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose

torch.transpose(f,0,1) #swapping zero with one. 

tensor([[4, 1],
        [2, 1],
        [7, 5]])

In [ ]:
# determinant
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
torch.det(h)

tensor(24.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.4583, -0.8333,  0.0417],
        [ 0.0833,  0.6667, -0.0833],
        [-0.1667, -0.3333,  0.1667]])

**5 . Comaprision Operartions**

In [15]:
i=torch.randint(size=(2,3),low=0,high=9)
j=torch.randint(size=(2,3),low=0,high=9)

In [ ]:
# greater than
i>j

tensor([[ True,  True, False],
        [ True, False, False]])

In [ ]:
# less than 
i<j

tensor([[False, False,  True],
        [False, False,  True]])

In [ ]:
# not equal to or equal to
i!=j

tensor([[ True,  True,  True],
        [ True, False,  True]])

In [ ]:
# greater than equal to or less than equal to and so on.

i<=j


tensor([[False, False,  True],
        [False,  True,  True]])

**6. Special function**

In [18]:
k=torch.randint(size=(2,3),low=0,high=12,dtype=torch.float32)
k

tensor([[ 7.,  8.,  0.],
        [11.,  5.,  9.]])

In [19]:
# log
torch.log(k)

tensor([[1.9459, 2.0794,   -inf],
        [2.3979, 1.6094, 2.1972]])

In [20]:
# exponential (exp)
torch.exp(k)

tensor([[1.0966e+03, 2.9810e+03, 1.0000e+00],
        [5.9874e+04, 1.4841e+02, 8.1031e+03]])

In [21]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 2.8284, 0.0000],
        [3.3166, 2.2361, 3.0000]])

In [22]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9997, 0.5000],
        [1.0000, 0.9933, 0.9999]])

In [23]:
# softmax
torch.softmax(k,dim=0)

tensor([[1.7986e-02, 9.5257e-01, 1.2339e-04],
        [9.8201e-01, 4.7426e-02, 9.9988e-01]])

In [24]:
# relu

torch.relu(k)

tensor([[ 7.,  8.,  0.],
        [11.,  5.,  9.]])

# Vector matrix and Tensor

The only thing that makes the Matrix "different" from the Vector is a tiny piece of metadata metadata called the **stride**. The stride tells the system: *"To move down one row, skip 3 slots in memory."* By changing the stride metadata, a computer can instantly view a Vector as a Matrix, or a Matrix as a 3D Tensor (`tensor.view()` or `tensor.reshape()`) **without moving or changing a single byte of the actual data.**

### Summary
They have different names because human language developed hierarchically as we discovered higher dimensions of geometry. But logically, they are a continuum. A vector is just a matrix with a width of 1; a matrix is just a 3D tensor with a depth of 1. It is Tensors all the way down.

**Inplace Operations**

In [31]:
# two tensors
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
m+n

tensor([[0.9516, 0.2855, 0.2324],
        [0.9141, 0.7668, 0.1659]])


tensor([[1.3909, 0.5098, 1.1259],
        [0.9638, 0.9448, 0.4670]])

In [32]:
m.add_(n)


tensor([[1.3909, 0.5098, 1.1259],
        [0.9638, 0.9448, 0.4670]])

In [34]:
torch.relu(m)

tensor([[1.3909, 0.5098, 1.1259],
        [0.9638, 0.9448, 0.4670]])

In [36]:
#instead
# to inplace permanent change just put underscore. 
m.relu_()

tensor([[1.3909, 0.5098, 1.1259],
        [0.9638, 0.9448, 0.4670]])

**copying a tensor**

In [37]:
a=torch.rand(2,3)
a

tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [38]:
b=a

In [39]:
b

tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [40]:
a[0][0]=0

In [ ]:
b
# b is also changed even we made copy. 

tensor([[0.0000, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [43]:
id(a)

2163785048976

In [44]:
id(b)

2163785048976

Means a and b is pointed in same memory location.  so to copy we use clone function.

In [45]:
b=a.clone()

**Tensor operation on GPU**

[test in collab]

In [46]:
torch.cuda.is_available()

False

In [48]:
device=torch.device("cuda")

In [ ]:
# creating tensor on GPU
torch.rand(2,3,device=device)

tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]])

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
b=a.to(device)

# it will give new tensor created in gpu

In [ ]:
import time
import torch
# size of the matrices
size=10000  # large size for performance comparison

# random  matrices on CPU
matrix_CPU1=torch.randn(size,size)
matrixCPU2=torch.randn(size,size)

# measure time on CPU

start_time=time.time()
rsult_cpu=torch.matmul(matrix_CPU1,matrixCPU2)
cpu_time=time.time()-start_time
print(f"time in cpu : {cpu_time:.4f}seconds")

# measure time on GPU

matrix_gpu1=matrix_CPU1.to("cuda")
matrix_gpu2=matrixCPU2.to("cuda")

start_time=time.time()
result_gpt=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time=time.time()-start_time

time in cpu : 1779685299.5042seconds


**Reshaping tensors**

In [1]:
import torch
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [2]:
# reshape

a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [3]:
# flatten

a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
b=torch.rand(2,3,4)
b

tensor([[[0.0957, 0.4031, 0.2505, 0.2036],
         [0.9835, 0.8509, 0.3871, 0.1554],
         [0.9975, 0.0451, 0.4693, 0.9157]],

        [[0.8416, 0.8544, 0.9663, 0.3510],
         [0.6718, 0.7623, 0.2071, 0.2736],
         [0.3904, 0.1989, 0.4713, 0.6766]]])

In [9]:
# permute (permutation of 2nd row, first row and last row)
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
c=torch.rand(226,226,3)
c.unsqueeze(1).shape
c.unsqueeze(2).shape



torch.Size([226, 226, 1, 3])

PyTorch Mechanics: `torch.unsqueeze`

The `unsqueeze` method is used for **dimension insertion**. It injects a new dimension of size 1 at a specified index without changing the underlying data or the total number of elements.

In [27]:
# squeze
d=torch.rand(1,20)
d.squeeze(0).shape # 0th position

torch.Size([20])

**Numpy and Pytorch**

In [35]:
import numpy as np
import torch

a=torch.tensor([1,2,3])

# converting in numpy array
b=a.numpy()

# similarly vice versa
c=np.array([1,2,3])
torch.from_numpy(c)

tensor([1, 2, 3])