# NN Module

```TEXT
 The Torch.nn module in Pytorch is a core library that gives wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and Training neural networks by offering pre built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and experimenting with model architectures. 
```

#### Key components of torch.nn

1. Modules (Layers)
    - nn.module: The base class for all neural networs modules. Custom model layers should subclass this class.
    - Common layers: Includes layers like nn.linear, nn.Conv2d(convolutional layer), nn.LSTM(recuurent layer) and many others.


2. Activation functions 
    - Functions like  nn.ReLU, nn.sigmoid and nn.Tanh intrduce non-linearities to the model allowing it to learn complex patterns.

3. Loss functions
    - Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss and nn.NLLLoss to quantift the difference between the models prediction and actual targets.

4. Container Modules
    - nn.sequential: A sequential container to stack layers in order

5. Regularization and Dropout
    - Layers like nn.Dropout and nn.BatchNorm2d help to prevent overfitting and improve the models quality to generalize to new data.

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn



# Create module class

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()   #“Call the parent class’s version of this method.”
        self.linear=nn.Linear(num_features,1)   #num_features as input ; single neuron
        # activation func
        self.sigmoid=nn.Sigmoid()

    def forward(self,features): 
        out=self.linear(features)  #calling linear layer first and send features
        out= self.sigmoid(out)

        return out

In [2]:
# Creating dataset 

features=torch.rand(10,5)

# Create model
model=Model(features.shape[1])

# call model for forward pass
model(features)  # model.forward() is not being used since it is not recommended.  just call as function

tensor([[0.5260],
        [0.4892],
        [0.5754],
        [0.5692],
        [0.4978],
        [0.5150],
        [0.5841],
        [0.5519],
        [0.4687],
        [0.5590]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights

model.linear.weight

Parameter containing:
tensor([[ 0.4242, -0.1485, -0.1885,  0.3113, -0.2785]], requires_grad=True)

```Python
pip install torchinfo

In [4]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Another example

In [5]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn



# Create module class

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()   #“Call the parent class’s version of this method.”
        self.linear1=nn.Linear(num_features,3)   
        # activation func
        self.relu=nn.ReLU()

        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features): 
        out=self.linear1(features)  #calling linear layer first and send features
        out= self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)

        return out
    

# Creating dataset 

features=torch.rand(10,5)

# Create model
model=Model(features.shape[1])

# call model for forward pass
model(features)  # model.forward() is not being used since it is not recommended.  just call as function

tensor([[0.5253],
        [0.5228],
        [0.5821],
        [0.4979],
        [0.4976],
        [0.4865],
        [0.5152],
        [0.4861],
        [0.4903],
        [0.5548]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear2.bias

Parameter containing:
tensor([-0.1161], requires_grad=True)

In [7]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

**Improved code**

- use of sequential containers

In [11]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn



# Create module class

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()

        self.network=nn.Sequential(
            nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
        )
    def forward(self,features): 
        out=self.network(features)

        return out
    

# Creating dataset 

features=torch.rand(10,5)

# Create model
model=Model(features.shape[1])

# call model for forward pass
model(features)  # model.forward() is not being used since it is not recommended.  just call as function

tensor([[0.2224],
        [0.2357],
        [0.2785],
        [0.2430],
        [0.2793],
        [0.2397],
        [0.2623],
        [0.2283],
        [0.2566],
        [0.2723]], grad_fn=<SigmoidBackward0>)

# The torch optim module

torch.optim is a module in pytorch that provides a variety of optimization algorithms used to update the parameters of model during training. 

It includes common optimizers like Stochastic Gradient Descent (SDG), Adam, RMSprop and more.
It handles weight updates efficiently including additional features like learning rate scheduling and weight decay (regularization).

The model Parameters() method in Pytorch retrieves an iterator over all the trainable parameters (weight and biases). In a model, These parameters are instances of torch.nn.Parameter and include

- weights : The weight of matrices of layers like nn.linear, nn.Conv2d etc
- Biases: The bias terms of layers (if they exist)

The optimizer uses these parameters to compute gradient and update them during parameters. 

```PYTHON
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)